const char PROGMEM strings_pedia[120][22] = {
  //0123456"},{"0123456789ABCDEF01234"},  {"0123456789ABCDEF01234"},  {"0123456789ABCDEF01234"},
  {"Egg"},    {"The very"},               {"beginning. Best"},        {"stats in the game."},
  {"Goob"},   {"Very curious,"},          {"but everything makes"},   {"it nervous."},
  {"Wibbur"}, {"Its two wiggly"},         {"feet are just going"},    {"with the flow."},
  {"Xorby"},  {"It's always"},            {"trying to use its"},      {"limbs to play!"},
  {"Snek"},   {"It might not"},           {"have any limbs, but"},    {"it's very clever."},
  {"Shansy"}, {"It sings a song"},        {"while it twirls its"},    {"tentacles around."},
  {"Moops"},  {"Shuffles around"},        {"on its suction-cup"},     {"feet and moos."},
  {"Hwooty"}, {"Staring into"},           {"space seems to be its"},  {"favorite pastime."},
  {"Flip"},   {"Can't fly, but"},         {"runs very fast every-"},  {"where it goes."},
  {"Lugerd"}, {"Gets grouchy"},           {"when it's not allowed"},  {"to hit things."},
  {"Shent"},  {"It's very smart,"},       {"but it also gets"},       {"bored very easily."},
  {"Culu"},   {"You can feel it"},        {"in your mind..."},        {""},
  {"Slorp"},  {"It hides in its"},        {"spiral shell when it"},   {"feels threatened."},
  {"Zeta"},   {"It's a slippery,"},       {"zippidy-zappy, shocky"},  {"water snake."},
  {"Butters"}, {"A highly mobile"},       {"source of specific"},     {"dairy products."},
  {"Tribbur"}, {"Nobody knows how"},      {"it eats food without"},   {"a mouth."},
  {"Corine"}, {"It always looks"},        {"like it's ready to be"},  {"photgraphed."},
  {"Pyre"},   {"A fiery attitude"},       {"to match it's fiery"},    {"body."},
  {"Rajur"},  {"It will destroy"},        {"anything that gets in"},  {"its way."},
  {"Crosh"},  {"It only moves to"},       {"hit things with its"},    {"hammer."},
  {""},     {""},             {""},             {""},
  {""},     {""},             {""},             {""},
  {""},     {""},             {""},             {""},
  {""},     {""},             {""},             {""},
  {""},     {""},             {""},             {""},
  {""},     {""},             {""},             {""},
  {""},     {""},             {""},             {""},
  {""},     {""},             {""},             {""},
  {""},     {""},             {""},             {""},
  {""},     {""},             {""},             {""}
};
